#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/BeatmapDifficulty.hpp"
#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/GameplayModifiers.hpp"
#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/GameplayModifiersModelSO.hpp"
#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/BeatmapDifficulty.hpp"
#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/IDifficultyBeatmap.hpp"
#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/IBeatmapLevel.hpp"
#include "../extern/BeatSaber-Quest-Codegen/include/GlobalNamespace/ScoreController.hpp"